# Generated by Django 2.1.4 on 2018-12-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('draft', 'Rascunho')], max_length=15),
        ),
    ]
